name: "Build"
on:
  workflow_call:
defaults:
  run:
    shell: bash


jobs:
  build-logto-docker:
    name: "Build LogTo Nginx Docker Image"
    runs-on: ubuntu-latest
    env: 
      IMAGE_NAME: ${{ github.repository }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: buildx
        with:
          install: true
          version: latest
      
      - name: Configure Docker image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ env.IMAGE_NAME }}
            registry.digitalocean.com/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=raw,value=staging-latest
            type=sha,format=long

      - name: Build LogTo image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          outputs: type=docker,dest=nginx-logto-staging.tar
          cache-from: type=gha
          cache-to: type=gha,mode=min  

      - name: Upload LogTo build image as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: nginx-logto-staging
          path: nginx-logto-staging.tar

  build-mcp-server-docker:
    name: "Build MCP Server Nginx Docker Image"
    runs-on: ubuntu-latest
    env: 
      IMAGE_NAME: 'nginx-mcp-server'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        id: buildx
        with:
          install: true
          version: latest
      
      - name: Configure Docker image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            registry.digitalocean.com/cheqd/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=raw,value=staging-latest
            type=sha,format=long
      
      - name: Build MCP Server image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.RemoteMCP
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          outputs: type=docker,dest=nginx-mcp-server-staging.tar
          cache-from: type=gha
          cache-to: type=gha,mode=min  

      - name: Upload MCP server build image as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: nginx-mcp-server-staging
          path: nginx-mcp-server-staging.tar
