name: "Deploy"
on:
  workflow_call:
defaults:
  run:
    shell: bash

jobs:
  deploy-logto-staging:
    name: "Deploy LogTo image"
    runs-on: ubuntu-latest
    env: 
      IMAGE_NAME: ${{ github.repository }}

    steps:
      - name: Install DigitalOcean CLI
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Login to DOCR
        run: doctl registry login --expiry-seconds 600

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Docker image
        uses: actions/download-artifact@v4
        with:
          name: nginx-logto-staging

      - name: Load Docker image
        run: docker image load --input nginx-logto-staging.tar

      - name: Push image to GitHub Container Registry
        run: docker image push --all-tags ghcr.io/${{ env.IMAGE_NAME }}

      - name: Push staging image to DOCR
        run: docker image push --all-tags registry.digitalocean.com/${{ env.IMAGE_NAME }}

  deploy-mcp-server-staging:
    name: "Deploy MCP Server image"
    runs-on: ubuntu-latest
    env: 
      IMAGE_NAME: 'cheqd/nginx-mcp-server'

    steps:
      - name: Install DigitalOcean CLI
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Login to DOCR
        run: doctl registry login --expiry-seconds 600

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Docker image
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.IMAGE_NAME }}-staging

      - name: Load Docker image
        run: docker image load --input ${{ env.IMAGE_NAME }}-staging.tar

      - name: Push staging image to DOCR
        run: docker image push --all-tags registry.digitalocean.com/${{ env.IMAGE_NAME }}
